spring:
  application:
    name: beacon-test
  # nacos地址
  cloud:
    nacos:
      discovery:
        server-addr: 172.29.205.122:8848
  # datasource
  datasource:
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://172.29.205.122:3306/beacon_cloud?characterEncoding=utf-8
    username: root
    password: Zjq24110649.
# 端口号
server:
  port: 20000

# mybatis
mybatis:
  configuration:
    map-underscore-to-camel-case: true